ProjectMvc.PL/Models/ErrorViewModel.cs
namespace ProjectMvc.PL.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProjectMvc.PL/Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectMvc.BLL.Interfaces;
using ProjectMvc.BLL.Repositories;
using ProjectMvc.DAL.Models;

namespace ProjectMvc.PL.Controllers
{
    public class DepartmentController : Controller
    {
        private IDepartmentRepository _departmentRepository;
        public DepartmentController( IDepartmentRepository departmentRepository)
        {
            _departmentRepository = departmentRepository;
        }
        public IActionResult Index()
        {
            var department = _departmentRepository.GetAll();
            return View(department);
        }

        [HttpGet]
        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        public IActionResult Create(Department department)
        {
            if (ModelState.IsValid)
            {
                _departmentRepository.Add(department);
                return RedirectToAction(nameof(Index));
            }

            return View(department);
        }

        public IActionResult Details(int? id, string ViewName= "Details")
        {
            if (id is null)
                return BadRequest();
            var department = _departmentRepository.GetById(id.Value);
            if (department is null)
                return NotFound();
            return View(ViewName , department);
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            //if (id is null)
            //    return BadRequest();
            //var department = _departmentRepository.GetById(id.Value);
            //if (department is null)
            //    return NotFound();
            return Details(id, "Edit");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Department department, [FromRoute] int id)
        {
            if (id != department.Id)
                return BadRequest();
            if (ModelState.IsValid)
            {
                try
                {
                    _departmentRepository.Update(department);
                    return RedirectToAction(nameof(Index));

                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }
            }

            return View(department);
        }

        public IActionResult Delete(int? id)
        {
            //if (id is null)
            //    return BadRequest();
            //var department = _departmentRepository.GetById(id.Value);
            //if (department is null)
            //    return NotFound();
            return Details(id, "Delete");
        }

        [HttpPost]
        public IActionResult Delete(Department department)
        {
            if (ModelState.IsValid)
            {
                _departmentRepository.Delete(department);
                return RedirectToAction(nameof(Index));
            }

            return View(department);
        }


    }
}

ProjectMvc.PL/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectMvc.BLL.Interfaces;
using ProjectMvc.BLL.Repositories;
using ProjectMvc.DAL.Models;

namespace ProjectMvc.PL.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IEmployeeRepository _employeeRepository;

        public EmployeeController(IEmployeeRepository employeeRepository)
        {
            _employeeRepository = employeeRepository;
        }
        public IActionResult Index()
        {
            var employee = _employeeRepository.GetAll();
            return View(employee);
        }

        [HttpGet]
        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        public IActionResult Create(Employee employee)
        {
            if (ModelState.IsValid)
            {
                _employeeRepository.Add(employee);
                return RedirectToAction(nameof(Index));
            }

            return View(employee);
        }

        public IActionResult Details(int? id, string ViewName = "Details")
        {
            if (id is null)
                return BadRequest();
            var employee = _employeeRepository.GetById(id.Value);
            if (employee is null)
                return NotFound();
            return View(ViewName, employee);
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            //if (id is null)
            //    return BadRequest();
            //var department = _departmentRepository.GetById(id.Value);
            //if (department is null)
            //    return NotFound();

            return Details(id, "Edit");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Employee employee, [FromRoute] int id)
        {
            if (id != employee.Id)
                return BadRequest();
            if (ModelState.IsValid)
            {
                try
                {
                    _employeeRepository.Update(employee);
                    return RedirectToAction(nameof(Index));

                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }
            }

            return View(employee);
        }

        public IActionResult Delete(int? id)
        {
            //if (id is null)
            //    return BadRequest();
            //var department = _departmentRepository.GetById(id.Value);
            //if (department is null)
            //    return NotFound();
            return Details(id, "Delete");
        }

        [HttpPost]
        public IActionResult Delete(Employee employee)
        {
            if (ModelState.IsValid)
            {
                _employeeRepository.Delete(employee);
                return RedirectToAction(nameof(Index));
            }

            return View(employee);
        }
    }
}

ProjectMvc.PL/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectMvc.PL.Models;
using System.Diagnostics;

namespace ProjectMvc.PL.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProjectMvc.PL/Views/Department/Create.cshtml
@model Department
@{
    ViewData["Title"] = "Create";
}

<h1>Create New Department</h1>
<br />
<form asp-action="Create">
    <div class="form-group">
        <label class="form-label" asp-for="Code"></label>
        <input class="form-control" asp-for="Code" />
        <span asp-validation-for="Code" class="text-danger"></span>
    </div>
    <br />

    <div class="form-group">
        <label class="form-label" asp-for="Name"></label>
        <input class="form-control" asp-for="Name" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <br />


    <div class="form-group">
        <label class="form-label" asp-for="DateOfCreation"></label>
        <input class="form-control" asp-for="DateOfCreation" />
        <span asp-validation-for="DateOfCreation" class="text-danger"></span>
    </div>

    <br />
    <center>
        <input type="submit" value="Submit" class="btn btn-primary" />
        <a asp-action="Index" class="btn btn-outline-secondary">Back To List</a>
    </center>
</form>

ProjectMvc.PL/Views/Department/Delete.cshtml
@model Department
@{
    ViewData["Title"] = "Delete";
}

<h1>Delete @Model.Name Department</h1>
<br />
<form asp-action="Delete">
    <div class="form-group">
        <label class="form-label" asp-for="Code"></label>
        <input readonly class="form-control" asp-for="Code" />
    </div>

    <br />

    <div class="form-group">
        <label class="form-label" asp-for="Name"></label>
        <input readonly class="form-control" asp-for="Name" />
    </div>

    <br />

    <div class="form-group">
        <label class="form-label" asp-for="DateOfCreation"></label>
        <input readonly class="form-control" asp-for="DateOfCreation" />
    </div>

    <br />
    <br />
    <center>
        <input type="submit" value="Delete" class="btn btn-danger" />

        <a asp-action="Index" class="btn btn-outline-secondary">Cansle</a>
    </center>
</form>

ProjectMvc.PL/Views/Department/Details.cshtml
@model Department
@{
    ViewData["Title"] = "Details";
}

<h1>Department @Model.Name Details</h1>

<br />

<div class="form-group">
    <label class="form-label" asp-for="Code"></label>
    <input readonly class="form-control" asp-for="Code" />
</div>

<br />

<div class="form-group">
    <label class="form-label" asp-for="Name"></label>
    <input readonly class="form-control" asp-for="Name" />
</div>

<br />

<div class="form-group">
    <label class="form-label" asp-for="DateOfCreation"></label>
    <input readonly class="form-control" asp-for="DateOfCreation" />
</div>

<br />
<br />
<center>
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-success">Eidt</a>
    <a asp-action="Index" class="btn btn-outline-secondary">Back To List</a>
</center>

ProjectMvc.PL/Views/Department/Edit.cshtml
@model Department
@{
    ViewData["Title"] = "Edit";
}

<h1> Edit @Model.Name Department </h1>

<br />
<div asp-validation-summary="All" class="alert alert-danger"></div>
<br />

<form asp-action="Edit">
    <div class="form-group">
        <label class="form-label" asp-for="Code"></label>
        <input class="form-control" asp-for="Code" />
        <span asp-validation-for="Code" class="text-danger"></span>
    </div>
    <br />

    <div class="form-group">
        <label class="form-label" asp-for="Name"></label>
        <input class="form-control" asp-for="Name" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <br />


    <div class="form-group">
        <label class="form-label" asp-for="DateOfCreation"></label>
        <input class="form-control" asp-for="DateOfCreation" />
        <span asp-validation-for="DateOfCreation" class="text-danger"></span>
    </div>

    <br />
    <center>
        <input type="submit" value="Save" class="btn btn-primary" />
        <a asp-action="Index" class="btn btn-outline-secondary">Back To List</a>
    </center>
</form>

ProjectMvc.PL/Views/Department/Index.cshtml
@model IEnumerable<Department>
@{
    ViewData["Title"] = "Index";
}

<br />


<a asp-action="Create" class="btn btn-primary">Create New Department</a>
<br />
<br />

@if (Model.Count() > 0)
{
    <h1>All Departments</h1>
    <table class="table table-striped table-hover mt-3">
        <thead>
            <tr>
                <td>@Html.DisplayNameFor(D => D.Code)</td>
                <td>@Html.DisplayNameFor(D => D.Name)</td>
                <td>@Html.DisplayNameFor(D => D.DateOfCreation)</td>
                <td>Details</td>
                <td>Update</td>
                <td>Delete</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var dept in Model)
            {
                <tr>
                    <td>@dept.Code</td>
                    <td>@dept.Name</td>
                    <td>@dept.DateOfCreation</td>
                    <partial name="_ButtonEmployeeDepartmentPartialView" model="@dept.Id"/>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <center>
        <div class="alert alert-primary">
            <h3>There Is No Departments</h3>
        </div>
    </center>
}

ProjectMvc.PL/Views/Employee/Create.cshtml
@model Employee
@{
    ViewData["Title"] = "Create";
}

<h1>Create New Employee</h1>
<br />
<form asp-action="Create">
    <partial name="PartialViews/EditCreateEmployeePartialView" model="Model" />


    <br />
    <center>
        <input type="submit" value="Create" class="btn btn-primary" />
        <a asp-action="Index" class="btn btn-outline-secondary">Back To List</a>
    </center>
</form>

@section validation
{
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

}

ProjectMvc.PL/Views/Employee/Delete.cshtml
@model Employee
@{
    ViewData["Title"] = "Delete";
}

<h1>Delete @Model.Name Employee</h1>
<br />
<form asp-action="Delete">
    <partial name="PartialViews/DeleteDetailsEmployeePartialView" model="Model" />


    <br />
    <br />
    <center>
        <input type="submit" value="Delete" class="btn btn-danger" />

        <a asp-action="Index" class="btn btn-outline-secondary">Cansle</a>
    </center>
</form>

ProjectMvc.PL/Views/Employee/Details.cshtml
@model Employee
@{
    ViewData["Title"] = "Details";
}

<h1>Employee @Model.Name Details</h1>

<br />

<br />

<partial name="PartialViews/DeleteDetailsEmployeePartialView" model="Model" />


<br />
<br />
<center>
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-success">Eidt</a>
    <a asp-action="Index" class="btn btn-outline-secondary">Back To List</a>
</center>

ProjectMvc.PL/Views/Employee/Edit.cshtml
@model Employee
@{
    ViewData["Title"] = "Edit";
}

<h1> Edit @Model.Name Employee </h1>

<br />
<div asp-validation-summary="All" class="alert alert-danger"></div>
<br />

<form asp-action="Edit">
    <partial name="PartialViews/EditCreateEmployeePartialView" model="Model" />

    <br />
    <center>
        <input type="submit" value="Save" class="btn btn-primary" />
        <a asp-action="Index" class="btn btn-outline-secondary">Back To List</a>
    </center>
</form>

@section validation
{
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

}

ProjectMvc.PL/Views/Employee/Index.cshtml
@model IEnumerable<Employee>
@{
    ViewData["Title"] = "Index";
}

<br />


<a asp-action="Create" class="btn btn-primary">Create New Employee</a>
<br />
<br />

@if (Model.Count() > 0)
{
    <h1>All Employees</h1>
    <table class="table table-striped table-hover mt-3">
        <thead>
            <tr>
                <td>@Html.DisplayNameFor(D => D.Name)</td>
                <td>@Html.DisplayNameFor(D => D.Age)</td>
                <td>@Html.DisplayNameFor(D => D.Address)</td>
                <td>@Html.DisplayNameFor(D => D.Email)</td>
                <td>@Html.DisplayNameFor(D => D.PhoneNumber)</td>
                <td>@Html.DisplayNameFor(D => D.Salary)</td>
                <td>@Html.DisplayNameFor(D => D.IsActive)</td>
                <td>@Html.DisplayNameFor(D => D.HiringDate)</td>
                <td>Details</td>
                <td>Update</td>
                <td>Delete</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var empl in Model)
            {
                <tr>
                    <td>@empl.Name</td>
                    <td>@empl.Age</td>
                    <td>@empl.Address</td>
                    <td>@Html.DisplayFor(M => empl.Email)</td>
                    <td>@empl.PhoneNumber</td>
                    <td>@Html.DisplayFor(M=>empl.Salary)</td>
                    <td>@Html.DisplayFor(M=>empl.IsActive)</td>
                    <td>@empl.HiringDate</td>
                    <partial name="_ButtonEmployeeDepartmentPartialView" model="@empl.Id" />

               </tr>
            }
        </tbody>
    </table>
}
else
{
    <center>
        <div class="alert alert-primary">
            <h3>There Is No Employees</h3>
        </div>
    </center>
}

ProjectMvc.PL/Views/Employee/PartialViews/DeleteDetailsEmployeePartialView.cshtml
@model Employee

<div class="form-group">
    <label class="form-label" asp-for="Name"></label>
    <input class="form-control" asp-for="Name" readonly />
</div>
<br />
<div class="form-group">
    <label class="form-label" asp-for="Age"></label>
    <input class="form-control" asp-for="Age" readonly />
</div>

<br />


<div class="form-group">
    <label class="form-label" asp-for="Address"></label>
    <input class="form-control" asp-for="Address" readonly />
</div>

<br />


<div class="form-group">
    <label class="form-label" asp-for="Email"></label>
    <input class="form-control" asp-for="Email" readonly />
</div>

<br />


<div class="form-group">
    <label class="form-label" asp-for="PhoneNumber"></label>
    <input class="form-control" asp-for="PhoneNumber" readonly />
</div>


<br />


<div class="form-group">
    <label class="form-label" asp-for="Salary"></label>
    <input class="form-control" asp-for="Salary" readonly />
</div>


<br />


<div class="form-group">
    <label class="form-check" asp-for="IsActive"></label>
    <input class="form-check" asp-for="IsActive" readonly />
</div>

<br />


<div class="form-group">
    <label class="form-label" asp-for="HiringDate"></label>
    <input asp-for="HiringDate" class="form-control" readonly />
</div>

ProjectMvc.PL/Views/Employee/PartialViews/EditCreateEmployeePartialView.cshtml
@model Employee

<div class="form-group">
    <label class="form-label" asp-for="Name"></label>
    <input class="form-control" asp-for="Name" />
    <span asp-validation-for="Name" class="text-danger"></span>
</div>
<br />

<div class="form-group">
    <label class="form-label" asp-for="Age"></label>
    <input class="form-control" asp-for="Age" />
    <span asp-validation-for="Age" class="text-danger"></span>
</div>

<br />


<div class="form-group">
    <label class="form-label" asp-for="Address"></label>
    <input class="form-control" asp-for="Address" />
    <span asp-validation-for="Address" class="text-danger"></span>
</div>

<br />


<div class="form-group">
    <label class="form-label" asp-for="Email"></label>
    <input class="form-control" asp-for="Email" />
    <span asp-validation-for="Email" class="text-danger"></span>
</div>

<br />


<div class="form-group">
    <label class="form-label" asp-for="PhoneNumber"></label>
    <input class="form-control" asp-for="PhoneNumber" />
    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
</div>


<br />


<div class="form-group">
    <label class="form-label" asp-for="Salary"></label>
    <input class="form-control" asp-for="Salary" />
    <span asp-validation-for="Salary" class="text-danger"></span>
</div>


<br />


<div class="form-group">
    <label class="form-check" asp-for="IsActive"></label>
    <input class="form-check" asp-for="IsActive" />
    <span asp-validation-for="IsActive" class="text-danger"></span>
</div>

<br />


<div class="form-group">
    <label class="form-label" asp-for="HiringDate"></label>
    <input asp-for="HiringDate" class="form-control" />
    <span asp-validation-for="HiringDate" class="text-danger"></span>
</div>

ProjectMvc.PL/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ProjectMvc.PL/Views/Shared/_ButtonEmployeeDepartmentPartialView.cshtml
@model int
<td><a class="btn btn-success" asp-action="Details" asp-route-id="@Model"><i class="fas fa-eye"></i>Details</a></td>
<td><a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model"><i class="fas fa-edit"></i>Update</a></td>
<td><a class="btn btn-danger" asp-action="Delete" asp-route-id="@Model"><i class="fas fa-remove"></i>Delete</a></td>

ProjectMvc.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjectMvc.PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjectMvc.PL.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProjectMvc.PL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ProjectMvc.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("validation", required: false)
</body>